type Photo {
  _id: ID
  photo: String!
  title: String!
  date: String!
  photo_location: String!
  createdDate: String
}

type Mutation {
  createPhotoPost(
    photo: String!
    title: String!
    date: String!
    photo_location: String!
  ): Photo!
  deletePhotoPost(photoId: ID!): Photo!
}

type Query {
  getAllPhotoPost: [Photo]!
}
